version: '3.5'

services:

  dind:
    build:
      context: tools/dind/
    image: dind 
    privileged: true

  sleeper:
    build:
      context: tools/sleeper/
    image: morningspace/lab-sleeper
